"""create ugc table

Revision ID: 890f7119320d
Revises: 
Create Date: 2026-05-26 01:12:58.223005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '890f7119320d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ugc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('active', 'hidden', 'pending')", name='check_ugc_status'),
    sa.CheckConstraint("type IN ('review', 'comment', 'rating')", name='check_ugc_type'),
    sa.CheckConstraint('rating IS NULL OR (rating >= 1 AND rating <= 10)', name='check_ugc_rating'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ugc', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ugc_movie_id'), ['movie_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ugc_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ugc', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ugc_user_id'))
        batch_op.drop_index(batch_op.f('ix_ugc_movie_id'))

    op.drop_table('ugc')
    # ### end Alembic commands ###
